{{- define "feature.autoInstrumentation.config.beyla" }}
{{- $endpoint := dict }}
{{- if .Values.beyla.traces.endpoint }}
  {{- $endpoint = dict "otel_traces_export" (dict "endpoint" .Values.beyla.traces.endpoint)}}
{{- end }}
{{- $preset := dict }}
{{- if and (eq .Values.beyla.preset "network") (not .Values.beyla.config.data.network) }}
  {{- $preset = dict "network" (dict "enable" true)}}
{{- end }}
{{- if and (eq .Values.beyla.preset "application") (not .Values.beyla.config.data.discovery) }}
  {{- $preset = dict "discovery" (dict "services" (list (dict "k8s_namespace" ".")))}}
{{- end }}
{{- merge .Values.beyla.config.data $endpoint $preset | toYaml }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beyla.fullname" .Subcharts.beyla }}
  namespace: {{ include "beyla.namespace" .Subcharts.beyla }}
  labels:
    {{- include "beyla.labels" .Subcharts.beyla | nindent 4 }}
    app.kubernetes.io/component: config
  {{- with .Values.beyla.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  beyla-config.yml: |-
    {{- include "feature.autoInstrumentation.config.beyla" . | nindent 4 }}
